# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:18
from __future__ import unicode_literals

from django.db import migrations


def load_currencies_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "world_currencies")
    call_command("loaddata", "crypto_currencies")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_currencies_from_fixture),
    ]
